version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=POSTGRE
      - POSTGRES_PASSWORD=POSTGRE
      - POSTGRES_DB=ESHOP
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local